### ISSUE TITLE
os

### ISSUE THREAD

**Issue by MRpringlesHandS** [Pierouge/FeurBot-Twitter#1]
Traceback (most recent call last):
  File "C:\Users\julie\Desktop\bot twitter\main.py", line 14, in <module>
    feurlist = os.listdir("feur")
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'feur'

du coup je comprend pas le code a cette instant

**Comment by MRpringlesHandS** [comment]
ouais nan du coup j'ai trouvé , faut mettee un r devant ex : os.listdir(r"C:\Users\julie\Desktop\twitter")
mais j'ai un autre probleme : twitter.error.TwitterError: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}] 
si j'ai bien compris en gros mon compte peut pas faire cette action ( j'ai du mal le creer ) 
j'ai aussi enlever la ligne pour les émojis ( global emoji_pattern
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002500-\U00002BEF"  # chinese char
                           u"\U00002702-\U000027B0"
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\U0001f926-\U0001f937"
                           u"\U00010000-\U0010ffff"
                           u"\u2640-\u2642"
                           u"\u2600-\u2B55"
                           u"\u200d"
                           u"\u23cf"
                           u"\u23e9"
                           u"\u231a"
                           u"\ufe0f"  # dingbats
                           u"\u3030"
                           "]+", flags=re.UNICODE) car ca faisait un probléme et je voyais pas ce que ca correspondais )

**Comment by MRpringlesHandS** [comment]
bah j'ai encore trouvé , il faut que je achete le " prenium " je crois que ya un truc dans le code qui est pas obligatoire et qui bloque 
, donc si un gars a réussis , même dans 2 ans , je suis preneur

**Comment by Pierouge** [comment]
> Traceback (most recent call last):
>   File "C:\Users\julie\Desktop\bot twitter\main.py", line 14, in <module>
>     feurlist = os.listdir("feur")
> FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'feur'
> 
> du coup je comprend pas le code a cette instant 

C'est pour mettre tes memes de feur à répondre en auto, le but était de rendre les réponses plus originales qu'un simple texte. Du coup tu les mets juste dans un dossier "feur" dans le même dossier que le script

**Comment by MRpringlesHandS** [comment]
ok merci , et du coup il faut bien que je prenne le prenium ou j'ai fait de la d dans le code ?

**Comment by MRpringlesHandS** [comment]
merci maintenant j'ai plus l'erreur a cause du feur mais par contre 
![image](https://user-images.githubusercontent.com/105736746/236689841-24f52351-945f-49c1-badf-dc3544b3cc52.png)

**Comment by MRpringlesHandS** [comment]
j'ai donc enlever comme toute a l'heure
mais après je sais pas comment faire 
![image](https://user-images.githubusercontent.com/105736746/236690016-eb2921d5-c821-47ba-82b5-6d8f2dfac51b.png)

**Comment by MRpringlesHandS** [comment]
et pour le getApi is not defined , j'ai ca pour tout les projets ( en tout cas les 2 que j'ai test )

**Comment by Pierouge** [comment]
> et pour le getApi is not defined , j'ai ca pour tout les projets ( en tout cas les 2 que j'ai test )
> 

Assure toi d'avoir bien installé le module listé dans le readme.md

**Comment by MRpringlesHandS** [comment]
le pip install twitter-python ? 
si c'est lui je l'ai bien installé 
j'ai aussi install pip install twitter pour être sur

**Comment by Pierouge** [comment]
> ouais nan du coup j'ai trouvé , faut mettee un r devant ex : os.listdir(r"C:\Users\julie\Desktop\twitter")
> mais j'ai un autre probleme : twitter.error.TwitterError: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}] 
> si j'ai bien compris en gros mon compte peut pas faire cette action ( j'ai du mal le creer ) 
> j'ai aussi enlever la ligne pour les émojis ( global emoji_pattern
> emoji_pattern = re.compile("["
>                            u"\U0001F600-\U0001F64F"  # emoticons
>                            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
>                            u"\U0001F680-\U0001F6FF"  # transport & map symbols
>                            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
>                            u"\U00002500-\U00002BEF"  # chinese char
>                            u"\U00002702-\U000027B0"
>                            u"\U00002702-\U000027B0"
>                            u"\U000024C2-\U0001F251"
>                            u"\U0001f926-\U0001f937"
>                            u"\U00010000-\U0010ffff"
>                            u"\u2640-\u2642"
>                            u"\u2600-\u2B55"
>                            u"\u200d"
>                            u"\u23cf"
>                            u"\u23e9"
>                            u"\u231a"
>                            u"\ufe0f"  # dingbats
>                            u"\u3030"
>                            "]+", flags=re.UNICODE) car ca faisait un probléme et je voyais pas ce que ca correspondais ) 

Assure toi d'avoir activé le mode Write and Read dans les permissions de l'application comme listé ici : https://developer.twitter.com/en/docs/apps/app-permissions

**Comment by MRpringlesHandS** [comment]
j'ai mit la 3 eme proposition write and read and je sais plus quoi 
c'est pour ca ?

**Comment by MRpringlesHandS** [comment]
ca : Read, write and access Direct Messages

**Comment by Pierouge** [comment]
> ca : Read, write and access Direct Messages

Direct message n'est pas nécessaire

**Comment by MRpringlesHandS** [comment]
ok je vais éssayer de l'enlever

**Comment by MRpringlesHandS** [comment]
![image](https://user-images.githubusercontent.com/105736746/236691791-3c61a06f-9092-4592-8a64-68b254cb2578.png)
ca aussi faut que je change ?

**Comment by MRpringlesHandS** [comment]
pour le name gatApi is not defined ca serais parcque j'ai mal instal les modules ?

**Comment by Pierouge** [comment]
> pour le name gatApi is not defined ca serais parcque j'ai mal instal les modules ?

Ça ou bien t'as supprimé la mauvaise ligne

**Comment by Pierouge** [comment]
> ![image](https://user-images.githubusercontent.com/105736746/236691791-3c61a06f-9092-4592-8a64-68b254cb2578.png)
> ca aussi faut que je change ?

Je ne suis pas sûr

**Comment by MRpringlesHandS** [comment]
je peut te add discord ? je trouve ca plus facile que github ?

**Comment by MRpringlesHandS** [comment]
sinon pour installer les modules c'est bien juste : pip install python-twitter dans le terminal ?

**Comment by MRpringlesHandS** [comment]
PapierAuLait#8113

**Comment by MRpringlesHandS** [comment]
et aussi 
![image](https://user-images.githubusercontent.com/105736746/236693879-c7ce3f02-dfec-426e-a17a-e6ebd16a15e5.png)
pourquoi ca me le met en gris ?

**Comment by MRpringlesHandS** [comment]
![image](https://user-images.githubusercontent.com/105736746/236694199-856e7e6c-5284-4dff-9602-46b452477052.png)
du coup je doit payer le prenium ?

**Comment by Pierouge** [comment]
> ![image](https://user-images.githubusercontent.com/105736746/236694199-856e7e6c-5284-4dff-9602-46b452477052.png) du coup je doit payer le prenium ?

Il semblerait que ça soit à présent obligatoire, ce qui n'était pas le cas autrefois.
